export {
  STATS_REFETCH_INTERVAL_MS,
  STATS_STALE_TIME_MS,
  BOOKINGS_STALE_TIME_MS,
  STATS_SKELETON_COUNT,
  BOOKINGS_SKELETON_COUNT,
  MOCK_ACTION_DELAY_MS,
  ADMIN_QUERY_KEYS,
  STATUS_BADGE_COLORS,
  STATUS_LABELS,
  ADMIN_MESSAGES,
  MOCK_VENUE_STATS,
  MOCK_ADMIN_BOOKINGS,
} from './venue-admin-defaults';
