"""initial schema

Revision ID: 339f120d53f3
Revises: 
Create Date: 2026-02-14 18:15:37.739586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "339f120d53f3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("role", sa.Enum("student_org", "venue_admin", name="user_role"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(role != 'student_org') OR (email LIKE '%@%.edu')", name="student_org_edu_email_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index("ix_users_role_email", "users", ["role", "email"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("fraternity", "sorority", "club", "other", name="organization_type"),
            nullable=False,
        ),
        sa.Column("university", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_owner_id"), "organizations", ["owner_id"], unique=False)
    op.create_table(
        "venues",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("bar", "restaurant", "event_space", "cafe", name="venue_type"),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("base_price_cents", sa.Integer(), nullable=False),
        sa.Column("address_street", sa.String(length=255), nullable=True),
        sa.Column("address_city", sa.String(length=100), nullable=True),
        sa.Column("address_state", sa.String(length=2), nullable=True),
        sa.Column("address_zip", sa.String(length=10), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("base_price_cents >= 0", name="venue_price_non_negative_check"),
        sa.CheckConstraint("capacity > 0", name="venue_capacity_positive_check"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venues_owner_id"), "venues", ["owner_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time", sa.Time(), nullable=False),
        sa.Column("guest_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "rejected", "completed", "cancelled", name="booking_status"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("guest_count > 0", name="booking_guest_count_positive_check"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "venue_id", "event_date", "event_time", name="unique_venue_datetime_booking"
        ),
    )
    op.create_index(op.f("ix_bookings_event_date"), "bookings", ["event_date"], unique=False)
    op.create_index(
        op.f("ix_bookings_organization_id"), "bookings", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(
        "ix_bookings_venue_date_time",
        "bookings",
        ["venue_id", "event_date", "event_time"],
        unique=False,
    )
    op.create_index(op.f("ix_bookings_venue_id"), "bookings", ["venue_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_venue_id"), table_name="bookings")
    op.drop_index("ix_bookings_venue_date_time", table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_organization_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_event_date"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_venues_owner_id"), table_name="venues")
    op.drop_table("venues")
    op.drop_index(op.f("ix_organizations_owner_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index("ix_users_role_email", table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
